### ISSUE TITLE
scripts like plotpowerjson.sh depend on scripts in /home/pi/bin/gp which are not available

### ISSUE THREAD

**Issue by tong67** [flux242/radiosonde#1]
Tried to generate powerlevel plot from power measure channel. It reports multiple scripts not found:
nc -luk 5676 | ./plotpowerjson.sh 
./plotpowerjson.sh: line 18: /home/pi/bin/gp/gnuplotblock.sh: No such file or directory
./plotpowerjson.sh: line 37: /home/pi/bin/gp/removecolumns.sh: No such file or directory
./plotpowerjson.sh: line 37: /home/pi/bin/gp/gnuplotblock.sh: No such file or directory

gnuplot is not one of the checked dependencies (is not required for correct work of decoding radiosondes).
scripts are most likely not part of gnuplot but convenience wrappers around it. Providing them as part of this project would be usefull for getting supporting script functional

**Comment by flux242** [comment]
as it is stated in the README the gnuplot related scripts can be found in https://github.com/flux242/dotfiles/tree/master/.bin/gp

**Comment by tong67** [comment]
Ah, I read the readme but missed that line. Sorry for that.

I havebeen able to successfully generate powerlevel and waterfall plots. Now waiting for balloon to be in range to receive signal above noise level (SAW filter is ordered but not delivered yet).
